// src/styles/screens/ProductDetailScreen.styles.ts
import { StyleSheet } from 'react-native';
import { colors } from '../colors';
import { spacing } from '../spacing';
import { commonStyles } from '../common';

export const productDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.agriBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.agriLight,
  },
  backButton: {
    padding: spacing.xs,
    color: colors.agriTextDark,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
  },
  wishlistButton: {
    padding: spacing.xs,
  },
  imageContainer: {
    backgroundColor: colors.white,
    padding: spacing.xl,
    alignItems: 'center',
    position: 'relative',
  },
  categoryBadge: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    backgroundColor: colors.agriPrimary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 12,
    zIndex: 1,
  },
  categoryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  productImage: {
    width: 250,
    height: 250,
  },
  imageIndicators: {
    flexDirection: 'row',
    marginTop: spacing.md,
    gap: spacing.xs,
  },
  indicatorActive: {
    width: 24,
    height: 8,
    backgroundColor: colors.agriPrimary,
    borderRadius: 4,
  },
  indicator: {
    width: 8,
    height: 8,
    backgroundColor: colors.agriLight,
    borderRadius: 4,
  },
  infoContainer: {
    padding: spacing.lg,
    paddingBottom: 100, // Espacio para los botones fijos
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  productName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.agriTextDark,
    flex: 1,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.agriLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 16,
  },
  ratingText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.agriTextDark,
    marginLeft: spacing.xs,
  },
  reviewsText: {
    fontSize: 12,
    color: colors.textTertiary,
    marginLeft: spacing.xs,
  },
  freshnessContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  freshnessText: {
    fontSize: 14,
    color: colors.agriTextLight,
    marginRight: spacing.md,
  },
  organicBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.agriPrimary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 12,
    gap: spacing.xs,
  },
  organicText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: 'bold',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
    gap: spacing.md,
  },
  currentPrice: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.agriTextDark,
  },
  discountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  originalPrice: {
    fontSize: 18,
    color: colors.textTertiary,
    textDecorationLine: 'line-through',
  },
  discountTag: {
    backgroundColor: colors.error,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 6,
  },
  discountText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
    marginBottom: spacing.md,
  },
  quantityOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  quantityOption: {
    backgroundColor: colors.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.agriLight,
    minWidth: 80,
    alignItems: 'center',
  },
  quantityOptionSelected: {
    borderColor: colors.agriPrimary,
    backgroundColor: colors.agriLight,
  },
  quantityLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textTertiary,
    marginBottom: spacing.xs,
  },
  quantityLabelSelected: {
    color: colors.agriPrimary,
  },
  quantityPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.agriTextDark,
  },
  discountBadge: {
    fontSize: 11,
    color: colors.success,
    marginTop: spacing.xs,
  },
  quantitySelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: spacing.md,
    borderRadius: 12,
    marginBottom: spacing.lg,
    ...commonStyles.shadow,
  },
  quantityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.agriTextDark,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  counterButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.agriLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterValue: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
    minWidth: 30,
    textAlign: 'center',
  },
  descriptionContainer: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 16,
    marginBottom: spacing.lg,
    ...commonStyles.shadow,
  },
  descriptionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
    marginBottom: spacing.md,
  },
  productDescription: {
    fontSize: 15,
    color: colors.textTertiary,
    lineHeight: 24,
  },
  featuresContainer: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 16,
    marginBottom: spacing.lg,
    ...commonStyles.shadow,
  },
  featuresTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
    marginBottom: spacing.md,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  featureText: {
    fontSize: 14,
    color: colors.textTertiary,
    flex: 1,
  },
  nutritionContainer: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 16,
    marginBottom: spacing.xl,
    ...commonStyles.shadow,
  },
  nutritionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  nutritionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  nutritionItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: colors.agriLight,
    padding: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
  },
  nutritionValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.agriPrimary,
    marginBottom: spacing.xs,
  },
  nutritionLabel: {
    fontSize: 12,
    color: colors.textTertiary,
    textAlign: 'center',
  },
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.agriLight,
    ...commonStyles.shadow,
  },
  totalPriceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.agriTextDark,
  },
  totalPrice: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.agriPrimary,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.md,
    borderRadius: 12,
    gap: spacing.sm,
  },
  addToCartButton: {
    backgroundColor: colors.agriPrimary,
  },
  buyNowButton: {
    backgroundColor: colors.agriDark,
  },
  actionButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
});